Repository PrivateBin/PrivateBin, pull requests merged in 2021-04, with the labels that each got.

#775 Transmit cookie only over HTTPS
  CHANGELOG.md
  js/privatebin.js
  lib/Controller.php
  tpl/bootstrap.php
  tpl/page.php
Labels: enhancement, security/privacy

#777 Add base URL as default CSP restriction
  cfg/conf.sample.php
  lib/Configuration.php
Labels: security/privacy

#774 Add download button (for paste text)
  CHANGELOG.md
  css/privatebin.css
  i18n/ar.json
  i18n/bg.json
  i18n/ca.json
  i18n/cs.json
  i18n/de.json
  i18n/el.json
  i18n/en.json
  i18n/es.json
  i18n/et.json
  i18n/fr.json
  i18n/he.json
  i18n/hi.json
  i18n/hu.json
  i18n/id.json
  i18n/it.json
  i18n/ja.json
  i18n/ku.json
  i18n/la.json
  i18n/lt.json
  i18n/nl.json
  i18n/no.json
  i18n/oc.json
  i18n/pl.json
  i18n/pt.json
  i18n/ru.json
  i18n/sl.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh.json
  js/privatebin.js
  tpl/bootstrap.php
  tpl/page.php
Labels: UI/UX, enhancement
